apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMybHRZMkZ5YVc5MU9rZHlZWFIwWlRJeVhnPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson